# Generated by Django 4.1.3 on 2022-12-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_answer_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.user')),
            ],
        ),
    ]
