# Generated by Django 4.1.3 on 2022-12-13 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_rename_user_users_alter_useranswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcq.question'),
            preserve_default=False,
        ),
    ]
