# Generated by Django 4.1.3 on 2022-12-14 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcq', '0006_useranswer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_answers', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('ratio', models.IntegerField(default=0)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.questionset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
